In [91]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
d_country = pd.read_csv("country_2023.csv")

d_country

      Open  High   Low  Close  Inflation      country ISO3        date
0     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-01-01
1     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-02-01
2     0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-03-01
3     0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG  2007-04-01
4     0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG  2007-05-01
...    ...   ...   ...    ...        ...          ...  ...         ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep.  YEM  2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep.  YEM  2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep.  YEM  2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep.  YEM  2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep.  YEM  2023-10-01

[4798 rows x 8 columns]

In [93]:
d_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4798 entries, 0 to 4797
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Open       4734 non-null   float64
 1   High       4734 non-null   float64
 2   Low        4734 non-null   float64
 3   Close      4734 non-null   float64
 4   Inflation  4434 non-null   float64
 5   country    4798 non-null   object
 6   ISO3       4798 non-null   object
 7   date       4798 non-null   object
dtypes: float64(5), object(3)
memory usage: 300.0+ KB

cambiar nombres de las columnas
cambiar fechas de object a datetime

In [94]:
names_columns = ["open", "high", "low", "close", "inflation", "country", "iso3", "date"]
d_country.columns = names_columns
d_country

      open  high   low  close  inflation      country iso3        date
0     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-01-01
1     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-02-01
2     0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-03-01
3     0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG  2007-04-01
4     0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG  2007-05-01
...    ...   ...   ...    ...        ...          ...  ...         ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep.  YEM  2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep.  YEM  2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep.  YEM  2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep.  YEM  2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep.  YEM  2023-10-01

[4798 rows x 8 columns]

In [95]:
#cambio de obect a datetime
d_country["date"] = pd.to_datetime(d_country["date"])
d_country

      open  high   low  close  inflation      country iso3       date
0     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-01-01
1     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-02-01
2     0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-03-01
3     0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG 2007-04-01
4     0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG 2007-05-01
...    ...   ...   ...    ...        ...          ...  ...        ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep.  YEM 2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep.  YEM 2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep.  YEM 2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep.  YEM 2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep.  YEM 2023-10-01

[4798 rows x 8 columns]

In [ ]:
#eliminar duplicados
d_country=d_country.drop_duplicates()
d_country

      open  high   low  close  inflation      country iso3       date
0     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-01-01
1     0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-02-01
2     0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG 2007-03-01
3     0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG 2007-04-01
4     0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG 2007-05-01
...    ...   ...   ...    ...        ...          ...  ...        ...
4793  2.74  2.78  2.70   2.75      -0.28  Yemen, Rep.  YEM 2023-06-01
4794  2.79  2.83  2.75   2.81      -1.85  Yemen, Rep.  YEM 2023-07-01
4795  2.85  2.89  2.81   2.83      -3.17  Yemen, Rep.  YEM 2023-08-01
4796  2.86  2.97  2.82   2.97       1.68  Yemen, Rep.  YEM 2023-09-01
4797  3.06  3.11  2.98   2.98       3.76  Yemen, Rep.  YEM 2023-10-01

[4798 rows x 8 columns]

In [97]:
d_country.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4798 entries, 0 to 4797
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   open       4734 non-null   float64
 1   high       4734 non-null   float64
 2   low        4734 non-null   float64
 3   close      4734 non-null   float64
 4   inflation  4434 non-null   float64
 5   country    4798 non-null   object
 6   iso3       4798 non-null   object
 7   date       4798 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(5), object(2)
memory usage: 300.0+ KB

In [98]:
details = pd.read_csv("details_2023.csv")
details

,country,iso3,components,currency,start_date_observations,end_date_observations,number_of_markets_modeled,number_of_markets_covered,number_of_food_items,number_of_observations_food,...,total_food_price_increase_since_start_date,average_annualized_food_inflation,maximum_food_drawdown,average_annualized_food_volatility,average_monthly_food_price_correlation_between_markets,average_annual_food_price_correlation_between_markets,Rsquared_individual_food_items,Rsquared_individual_other_items,index_confidence_score,imputation_model
0,Afghanistan,AFG,"Bread (1 KG, Index Weight = 1), Rice (Low Qual...",AFN,Jan 2007,Sep 2023,40,40,3,"bread: 2318, rice: 2701, wheat: 2682",...,167.97%,6.06%,-40.67%,7.93%,0.62,0.87,"bread: 0.94, rice: 0.89, wheat: 0.93","exchange_rate_wfp: 1, fuel_diesel: 0.97, wage_...",0.92,"bread: cubist (Andree, 2021), rice: two-stage ..."
1,Burundi,BDI,"Bananas (1 KG, Index Weight = 1), Beans (1 KG,...",BIF,Jan 2007,Aug 2023,72,72,10,"bananas: 5344, beans: 5963, cassava_flour: 594...",...,254.94%,7.86%,-30.77%,12.03%,0.60,0.83,"bananas: 0.88, beans: 0.9, cassava_flour: 0.89...",:,0.90,"bananas: two-stage cubist (Andree and Pape, 20..."
2,Burkina Faso,BFA,"Maize (White) (1 KG, Index Weight = 1), Millet...",XOF,Jan 2007,Jul 2023,64,64,3,"maize: 6615, millet: 7618, sorghum: 7177",...,201.25%,6.81%,-36.7%,13.71%,0.57,0.80,"maize: 0.84, millet: 0.83, sorghum: 0.81",:,0.83,"maize: cubist (Andree, 2021), millet: cubist (..."
3,Central African Republic,CAF,"Cassava (Cossette) (1 KG, Index Weight = 1), M...",XAF,Jan 2007,Jun 2023,42,42,5,"cassava: 2259, maize: 2025, meat_beef: 2147, o...",...,134.62%,5.22%,-24.85%,13.74%,0.39,0.59,"cassava: 0.89, maize: 0.88, meat_beef: 0.95, o...",:,0.89,"cassava: cubist (Andree, 2021), maize: cubist ..."
4,Cameroon,CMR,"Bananas (12 KG, Index Weight = 0.08), Cassava ...",XAF,Apr 2010,Aug 2023,83,83,10,"bananas: 621, cassava: 624, cocoyam: 624, fish...",...,39.02%,2.47%,-2.79%,1.84%,0.25,0.67,"bananas: 0.96, cassava: 0.96, cocoyam: 0.98, f...",:,0.98,"bananas: two-stage cubist (Andree and Pape, 20..."
5,"Congo, Dem. Rep.",COD,"Beans (1 KG, Index Weight = 1), Cassava (Cosse...",CDF,Jan 2007,Jan 2023,86,86,17,"beans: 3310, cassava: 2665, cassava_flour: 325...",...,193.41%,6.64%,-15.73%,6.99%,0.26,0.55,"beans: 0.84, cassava: 0.93, cassava_flour: 0.8...",exchange_rate_wfp: 0.98,0.93,"beans: cubist (Andree, 2021), cassava: two-sta..."
6,"Congo, Rep.",COG,"Beans (White) (1 KG, Index Weight = 1), Cassav...",XAF,Jan 2011,Apr 2022,13,13,4,"beans: 643, cassava_flour: 564, oil: 484, rice...",...,17.06%,1.24%,-8.13%,5.45%,0.19,0.27,"beans: 0.86, cassava_flour: 0.8, oil: 0.79, ri...",:,0.82,"beans: two-stage cubist (Andree and Pape, 2023..."
7,"Gambia, The",GMB,"Apples (Red) (1 KG, Index Weight = 1), Bananas...",GMD,Jan 2007,Jul 2023,28,28,26,"apples: 1556, bananas: 1672, beans: 1668, brea...",...,195.4%,6.68%,-20.83%,7.15%,0.56,0.84,"apples: 0.95, bananas: 0.92, beans: 0.91, brea...","fuel_diesel: 0.98, fuel_petrol_gasoline: 0.98",0.94,"apples: two-stage cubist (Andree and Pape, 202..."
8,Guinea-Bissau,GNB,"Millet (1 KG, Index Weight = 1), Oil (Vegetabl...",XOF,Jun 2007,Aug 2023,45,45,5,"millet: 1011, oil: 1822, rice: 1811, sorghum: ...",...,30.87%,1.62%,-28.04%,11.77%,0.79,0.92,"millet: 0.79, oil: 0.96, rice: 0.93, sorghum: ...",:,0.89,"millet: cubist (Andree, 2021), oil: cubist (An..."
9,Haiti,HTI,"Beans (Black) (1 Marmite, Index Weight = 0.37)...",HTG,Jan 2007,Jun 2023,9,9,8,"beans: 1166, maize_meal: 1727, oil: 1058, past...",...,604.41%,12.36%,-31.98%,11.66%,0.52,0.91,"beans: 0.93, maize_meal: 0.84, oil: 0.96, past...",:,0.95,"beans: two-stage cubist (Andree and Pape, 2023..."
10,Iraq,IRQ,"Beans (White) (1 KG, Index Weight = 1), Bread ...",IQD,Jan 2012,Sep 2023,20,20,18,"beans: 1397, bread: 2230, cheese: 1349, dates:...",...,15.7%,1.25%,-14.16%,3.64%,0.22,0.37,"beans: 0.97, bread: 0.98, cheese: 0.96, dates:...","fuel_gas: 0.99, fuel_kerosene: 0.97, fuel_petr...",0.97,"beans: two-stage cubist (Andree and Pape, 2023..."
11,Lao PDR,LAO,"Eggs (1 Unit, Index Weight = 12), Fish (Catfis...",LAK,Feb 2009,Jul 2023,17,17,11,"eggs: 1800, fish_catfish: 1712, fish_tilapia: ...",...,154.05%,6.56%,-7.92%,3.6%,0.36,0.79,"eggs: 0.99, fish_catfish: 0.97, fish_tilapia: ...","fuel_diesel: 0.92, fuel_petrol_gasoline: 0.98",0.99,"eggs: cubist (Andree, 2021), fish_catfish: two..."
12,Lebanon,LBN,"Beans (White) (1 KG, Index Weight = 1), Bread ...",LBP,Jan 2012,Aug 2023,27,27,22,"beans: 2927, bread: 2767, bulgur: 2937, cabbag...",...,5802.64%,41.49%,-12.13%,18.17%,0.77,0.99,"beans: 0.92, bread: 0.98, bulgur: 0.95, cabbag...","fuel_diesel: 1, fuel_gas: 1, fuel_petrol_gasol...",0.94,"beans: cubist (Andree, 2021), bread: cubist (A..."
13,Liberia,LBR,"Cassava (Fresh) (50 KG, Index Weight = 0.02), ...",LRD,Jan 2007,Aug 2020,24,24,4,"cassava: 1336, cowpeas: 1396, oil: 1872, rice:...",...,248.64%,7.74%,-10.82%,7.98%,0.28,0.60,"cassava: 0.88, cowpeas: 0.94, oil: 0.92, rice:...",fuel_petrol_gasoline: 0.93,0.94,"cassava: two-stage cubist (Andree and Pape, 20..."
14,Mali,MLI,"Beans (Niebe) (1 KG, Index Weight = 1), Maize ...",XOF,Jan 2007,Jun 2023,127,127,5,"beans: 7511, maize: 9990, millet: 13695, rice:...",...,80.17%,3.58%,-38.68%,8.26%,0.50,0.82,"beans: 0.92, maize: 0.91, millet: 0.91, rice: ...",:,0.92,"beans: cubist (Andree, 2021), maize: cubist (A..."
15,Myanmar,MMR,"Pulses (1 KG, Index Weight = 1), Rice (Low Qua...",MMK,Jan 2008,Aug 2023,228,228,3,"pulses: 5466, rice: 7818, salt: 7126",...,402.34%,10.79%,-23.71%,9.89%,0.26,0.65,"pulses: 0.91, rice: 0.9, salt: 0.86",:,0.89,"pulses: cubist (Andree, 2021), rice: cubist (A..."
16,Mozambique,MOZ,"Cowpeas (1 KG, Index Weight = 1), Maize (White...",MZN,Jan 2007,Feb 2023,99,99,7,"cowpeas: 3669, maize: 4230, maize_meal: 3158, ...",...,243.02%,7.64%,-22.6%,6.6%,0.43,0.88,"cowpeas: 0.77, maize: 0.94, maize_meal: 0.93, ...",:,0.93,"cowpeas: cubist (Andree, 2021), maize: cubist ..."
17,Niger,NER,"Millet (1 KG, Index Weight = 1), Rice (Importe...",XOF,Jan 2007,Jul 2023,79,79,3,"millet: 11754, rice: 11071, sorghum: 10644",...,63.73%,2.99%,-23.76%,9.54%,0.44,0.76,"millet: 0.86, rice: 0.94, sorghum: 0.83",:,0.89,"millet: cubist (Andree, 2021), rice: cubist (A..."
18,Nigeria,NGA,"Cassava Meal (Gari, Yellow) (100 KG, Index Wei...",NGN,Jan 2007,Jan 2023,35,35,8,"cassava_meal: 1255, cowpeas: 1536, gari: 1430,...",...,275.01%,8.21%,-37.05%,11.84%,0.83,0.97,"cassava_meal: 0.97, cowpeas: 0.95, gari: 0.97,...","fuel_diesel: 0.98, fuel_petrol_gasoline: 0.99",0.95,cassava_meal: two-stage cubist (Andree and Pap...
19,Sudan,SDN,"Millet (3.5 KG, Index Weight = 0.29), Sorghum ...",SDG,Jan 2007,Aug 2023,17,17,4,"millet: 2133, sorghum: 1662, sorghum_food_aid:...",...,159165.63%,55.3%,-12.16%,24.77%,0.64,0.95,"millet: 0.93, sorghum: 0.93, sorghum_food_aid:...",:,0.93,"millet: cubist (Andree, 2021), sorghum: cubist..."
20,Somalia,SOM,"Maize (White) (1 KG, Index Weight = 1), Milk (...",SOS,Jan 2007,Jul 2023,44,44,5,"maize: 2444, milk: 744, oil: 819, rice: 2558, ...",...,123.12%,4.91%,-37.03%,9.54%,0.58,0.89,"maize: 0.93, milk: 0.88, oil: 0.91, rice: 0.88...","exchange_rate_wfp: 0.96, fuel_diesel: 0.9",0.90,"maize: cubist (Andree, 2021), milk: two-stage ..."
21,South Sudan,SSD,"Beans (Red) (1 KG, Index Weight = 1), Cassava ...",SSP,Jan 2007,Aug 2023,30,30,9,"beans: 2067, cassava: 534, groundnuts: 1569, m...",...,63524.56%,47.02%,-29.43%,22.75%,0.67,0.97,"beans: 0.91, cassava: 0.91, groundnuts: 0.88, ...","fuel_diesel: 0.9, fuel_petrol_gasoline: 0.9",0.90,"beans: cubist (Andree, 2021), cassava: two-sta..."
22,Syrian Arab Republic,SYR,"Apples (1 KG, Index Weight = 1), Bananas (1 KG...",SYP,Feb 2011,Jul 2023,97,97,24,"apples: 3631, bananas: 3479, beans: 4117, brea...",...,4135.12%,34.15%,-13.96%,12.68%,0.60,0.96,"apples: 0.91, bananas: 0.91, beans: 0.96, brea...","exchange_rate_wfp: 0.98, fuel_diesel: 0.97, fu...",0.95,"apples: two-stage cubist (Andree and Pape, 202..."
23,Chad,TCD,"Maize (White) (1 KG, Index Weight = 1), Millet...",XAF,Jan 2007,Aug 2023,62,62,4,"maize: 2885, millet: 4683, rice: 2096, sorghum...",...,68.28%,3.16%,-32.67%,12.58%,0.58,0.79,"maize: 0.84, millet: 0.85, rice: 0.95, sorghum...","livestockgoat_castrated_male: 0.71, livestocks...",0.89,"maize: two-stage cubist (Andree and Pape, 2023..."
24,"Yemen, Rep.",YEM,"Beans (Kidney Red) (1 KG, Index Weight = 1), E...",YER,Jan 2009,Jul 2023,24,24,15,"beans: 2295, eggs: 2239, lentils: 2211, millet...",...,524.33%,13.22%,-14.88%,10.65%,0.55,0.75,"beans: 0.94, eggs: 0.97, lentils: 0.93, millet...","exchange_rate_wfp: 0.99, fuel_diesel: 0.91, fu...",0.95,"beans: cubist (Andree, 2021), eggs: cubist (An..."

In [99]:
details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 23 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   country                                                 25 non-null     object
 1   iso3                                                    25 non-null     object
 2   components                                              25 non-null     object
 3   currency                                                25 non-null     object
 4   start_date_observations                                 25 non-null     object
 5   end_date_observations                                   25 non-null     object
 6   number_of_markets_modeled                               25 non-null     int64
 7   number_of_markets_covered                               25 non-null     int64
 8   number_of_food_items                                    25 non-null     int64
 9   number_of_observations_food                             25 non-null     object
 10  number_of_observations_other                            25 non-null     object
 11  data_coverage_food                                      25 non-null     object
 12  data_coverage_previous_12_months_food                   25 non-null     object
 13  total_food_price_increase_since_start_date              25 non-null     object
 14  average_annualized_food_inflation                       25 non-null     object
 15  maximum_food_drawdown                                   25 non-null     object
 16  average_annualized_food_volatility                      25 non-null     object
 17  average_monthly_food_price_correlation_between_markets  25 non-null     float64
 18  average_annual_food_price_correlation_between_markets   25 non-null     float64
 19  Rsquared_individual_food_items                          25 non-null     object
 20  Rsquared_individual_other_items                         25 non-null     object
 21  index_confidence_score                                  25 non-null     float64
 22  imputation_model                                        25 non-null     object
dtypes: float64(3), int64(3), object(17)
memory usage: 4.6+ KB

cambiar start_date_observations y end_date_observations  de object a datetime

In [100]:
details["start_date_observations"] = pd.to_datetime(details["start_date_observations"], format="%b %Y")
details.head(1)

,country,iso3,components,currency,start_date_observations,end_date_observations,number_of_markets_modeled,number_of_markets_covered,number_of_food_items,number_of_observations_food,...,total_food_price_increase_since_start_date,average_annualized_food_inflation,maximum_food_drawdown,average_annualized_food_volatility,average_monthly_food_price_correlation_between_markets,average_annual_food_price_correlation_between_markets,Rsquared_individual_food_items,Rsquared_individual_other_items,index_confidence_score,imputation_model
0,Afghanistan,AFG,"Bread (1 KG, Index Weight = 1), Rice (Low Qual...",AFN,2007-01-01,Sep 2023,40,40,3,"bread: 2318, rice: 2701, wheat: 2682",...,167.97%,6.06%,-40.67%,7.93%,0.62,0.87,"bread: 0.94, rice: 0.89, wheat: 0.93","exchange_rate_wfp: 1, fuel_diesel: 0.97, wage_...",0.92,"bread: cubist (Andree, 2021), rice: two-stage ..."

In [105]:
details["end_date_observations"]=pd.to_datetime(details["end_date_observations"], format="%b %Y")
details

,country,iso3,components,currency,start_date_observations,end_date_observations,number_of_markets_modeled,number_of_markets_covered,number_of_food_items,number_of_observations_food,...,total_food_price_increase_since_start_date,average_annualized_food_inflation,maximum_food_drawdown,average_annualized_food_volatility,average_monthly_food_price_correlation_between_markets,average_annual_food_price_correlation_between_markets,Rsquared_individual_food_items,Rsquared_individual_other_items,index_confidence_score,imputation_model
0,Afghanistan,AFG,"Bread (1 KG, Index Weight = 1), Rice (Low Qual...",AFN,2007-01-01,2023-09-01,40,40,3,"bread: 2318, rice: 2701, wheat: 2682",...,167.97%,6.06%,-40.67%,7.93%,0.62,0.87,"bread: 0.94, rice: 0.89, wheat: 0.93","exchange_rate_wfp: 1, fuel_diesel: 0.97, wage_...",0.92,"bread: cubist (Andree, 2021), rice: two-stage ..."
1,Burundi,BDI,"Bananas (1 KG, Index Weight = 1), Beans (1 KG,...",BIF,2007-01-01,2023-08-01,72,72,10,"bananas: 5344, beans: 5963, cassava_flour: 594...",...,254.94%,7.86%,-30.77%,12.03%,0.60,0.83,"bananas: 0.88, beans: 0.9, cassava_flour: 0.89...",:,0.90,"bananas: two-stage cubist (Andree and Pape, 20..."
2,Burkina Faso,BFA,"Maize (White) (1 KG, Index Weight = 1), Millet...",XOF,2007-01-01,2023-07-01,64,64,3,"maize: 6615, millet: 7618, sorghum: 7177",...,201.25%,6.81%,-36.7%,13.71%,0.57,0.80,"maize: 0.84, millet: 0.83, sorghum: 0.81",:,0.83,"maize: cubist (Andree, 2021), millet: cubist (..."
3,Central African Republic,CAF,"Cassava (Cossette) (1 KG, Index Weight = 1), M...",XAF,2007-01-01,2023-06-01,42,42,5,"cassava: 2259, maize: 2025, meat_beef: 2147, o...",...,134.62%,5.22%,-24.85%,13.74%,0.39,0.59,"cassava: 0.89, maize: 0.88, meat_beef: 0.95, o...",:,0.89,"cassava: cubist (Andree, 2021), maize: cubist ..."
4,Cameroon,CMR,"Bananas (12 KG, Index Weight = 0.08), Cassava ...",XAF,2010-04-01,2023-08-01,83,83,10,"bananas: 621, cassava: 624, cocoyam: 624, fish...",...,39.02%,2.47%,-2.79%,1.84%,0.25,0.67,"bananas: 0.96, cassava: 0.96, cocoyam: 0.98, f...",:,0.98,"bananas: two-stage cubist (Andree and Pape, 20..."
5,"Congo, Dem. Rep.",COD,"Beans (1 KG, Index Weight = 1), Cassava (Cosse...",CDF,2007-01-01,2023-01-01,86,86,17,"beans: 3310, cassava: 2665, cassava_flour: 325...",...,193.41%,6.64%,-15.73%,6.99%,0.26,0.55,"beans: 0.84, cassava: 0.93, cassava_flour: 0.8...",exchange_rate_wfp: 0.98,0.93,"beans: cubist (Andree, 2021), cassava: two-sta..."
6,"Congo, Rep.",COG,"Beans (White) (1 KG, Index Weight = 1), Cassav...",XAF,2011-01-01,2022-04-01,13,13,4,"beans: 643, cassava_flour: 564, oil: 484, rice...",...,17.06%,1.24%,-8.13%,5.45%,0.19,0.27,"beans: 0.86, cassava_flour: 0.8, oil: 0.79, ri...",:,0.82,"beans: two-stage cubist (Andree and Pape, 2023..."
7,"Gambia, The",GMB,"Apples (Red) (1 KG, Index Weight = 1), Bananas...",GMD,2007-01-01,2023-07-01,28,28,26,"apples: 1556, bananas: 1672, beans: 1668, brea...",...,195.4%,6.68%,-20.83%,7.15%,0.56,0.84,"apples: 0.95, bananas: 0.92, beans: 0.91, brea...","fuel_diesel: 0.98, fuel_petrol_gasoline: 0.98",0.94,"apples: two-stage cubist (Andree and Pape, 202..."
8,Guinea-Bissau,GNB,"Millet (1 KG, Index Weight = 1), Oil (Vegetabl...",XOF,2007-06-01,2023-08-01,45,45,5,"millet: 1011, oil: 1822, rice: 1811, sorghum: ...",...,30.87%,1.62%,-28.04%,11.77%,0.79,0.92,"millet: 0.79, oil: 0.96, rice: 0.93, sorghum: ...",:,0.89,"millet: cubist (Andree, 2021), oil: cubist (An..."
9,Haiti,HTI,"Beans (Black) (1 Marmite, Index Weight = 0.37)...",HTG,2007-01-01,2023-06-01,9,9,8,"beans: 1166, maize_meal: 1727, oil: 1058, past...",...,604.41%,12.36%,-31.98%,11.66%,0.52,0.91,"beans: 0.93, maize_meal: 0.84, oil: 0.96, past...",:,0.95,"beans: two-stage cubist (Andree and Pape, 2023..."
10,Iraq,IRQ,"Beans (White) (1 KG, Index Weight = 1), Bread ...",IQD,2012-01-01,2023-09-01,20,20,18,"beans: 1397, bread: 2230, cheese: 1349, dates:...",...,15.7%,1.25%,-14.16%,3.64%,0.22,0.37,"beans: 0.97, bread: 0.98, cheese: 0.96, dates:...","fuel_gas: 0.99, fuel_kerosene: 0.97, fuel_petr...",0.97,"beans: two-stage cubist (Andree and Pape, 2023..."
11,Lao PDR,LAO,"Eggs (1 Unit, Index Weight = 12), Fish (Catfis...",LAK,2009-02-01,2023-07-01,17,17,11,"eggs: 1800, fish_catfish: 1712, fish_tilapia: ...",...,154.05%,6.56%,-7.92%,3.6%,0.36,0.79,"eggs: 0.99, fish_catfish: 0.97, fish_tilapia: ...","fuel_diesel: 0.92, fuel_petrol_gasoline: 0.98",0.99,"eggs: cubist (Andree, 2021), fish_catfish: two..."
12,Lebanon,LBN,"Beans (White) (1 KG, Index Weight = 1), Bread ...",LBP,2012-01-01,2023-08-01,27,27,22,"beans: 2927, bread: 2767, bulgur: 2937, cabbag...",...,5802.64%,41.49%,-12.13%,18.17%,0.77,0.99,"beans: 0.92, bread: 0.98, bulgur: 0.95, cabbag...","fuel_diesel: 1, fuel_gas: 1, fuel_petrol_gasol...",0.94,"beans: cubist (Andree, 2021), bread: cubist (A..."
13,Liberia,LBR,"Cassava (Fresh) (50 KG, Index Weight = 0.02), ...",LRD,2007-01-01,2020-08-01,24,24,4,"cassava: 1336, cowpeas: 1396, oil: 1872, rice:...",...,248.64%,7.74%,-10.82%,7.98%,0.28,0.60,"cassava: 0.88, cowpeas: 0.94, oil: 0.92, rice:...",fuel_petrol_gasoline: 0.93,0.94,"cassava: two-stage cubist (Andree and Pape, 20..."
14,Mali,MLI,"Beans (Niebe) (1 KG, Index Weight = 1), Maize ...",XOF,2007-01-01,2023-06-01,127,127,5,"beans: 7511, maize: 9990, millet: 13695, rice:...",...,80.17%,3.58%,-38.68%,8.26%,0.50,0.82,"beans: 0.92, maize: 0.91, millet: 0.91, rice: ...",:,0.92,"beans: cubist (Andree, 2021), maize: cubist (A..."
15,Myanmar,MMR,"Pulses (1 KG, Index Weight = 1), Rice (Low Qua...",MMK,2008-01-01,2023-08-01,228,228,3,"pulses: 5466, rice: 7818, salt: 7126",...,402.34%,10.79%,-23.71%,9.89%,0.26,0.65,"pulses: 0.91, rice: 0.9, salt: 0.86",:,0.89,"pulses: cubist (Andree, 2021), rice: cubist (A..."
16,Mozambique,MOZ,"Cowpeas (1 KG, Index Weight = 1), Maize (White...",MZN,2007-01-01,2023-02-01,99,99,7,"cowpeas: 3669, maize: 4230, maize_meal: 3158, ...",...,243.02%,7.64%,-22.6%,6.6%,0.43,0.88,"cowpeas: 0.77, maize: 0.94, maize_meal: 0.93, ...",:,0.93,"cowpeas: cubist (Andree, 2021), maize: cubist ..."
17,Niger,NER,"Millet (1 KG, Index Weight = 1), Rice (Importe...",XOF,2007-01-01,2023-07-01,79,79,3,"millet: 11754, rice: 11071, sorghum: 10644",...,63.73%,2.99%,-23.76%,9.54%,0.44,0.76,"millet: 0.86, rice: 0.94, sorghum: 0.83",:,0.89,"millet: cubist (Andree, 2021), rice: cubist (A..."
18,Nigeria,NGA,"Cassava Meal (Gari, Yellow) (100 KG, Index Wei...",NGN,2007-01-01,2023-01-01,35,35,8,"cassava_meal: 1255, cowpeas: 1536, gari: 1430,...",...,275.01%,8.21%,-37.05%,11.84%,0.83,0.97,"cassava_meal: 0.97, cowpeas: 0.95, gari: 0.97,...","fuel_diesel: 0.98, fuel_petrol_gasoline: 0.99",0.95,cassava_meal: two-stage cubist (Andree and Pap...
19,Sudan,SDN,"Millet (3.5 KG, Index Weight = 0.29), Sorghum ...",SDG,2007-01-01,2023-08-01,17,17,4,"millet: 2133, sorghum: 1662, sorghum_food_aid:...",...,159165.63%,55.3%,-12.16%,24.77%,0.64,0.95,"millet: 0.93, sorghum: 0.93, sorghum_food_aid:...",:,0.93,"millet: cubist (Andree, 2021), sorghum: cubist..."
20,Somalia,SOM,"Maize (White) (1 KG, Index Weight = 1), Milk (...",SOS,2007-01-01,2023-07-01,44,44,5,"maize: 2444, milk: 744, oil: 819, rice: 2558, ...",...,123.12%,4.91%,-37.03%,9.54%,0.58,0.89,"maize: 0.93, milk: 0.88, oil: 0.91, rice: 0.88...","exchange_rate_wfp: 0.96, fuel_diesel: 0.9",0.90,"maize: cubist (Andree, 2021), milk: two-stage ..."
21,South Sudan,SSD,"Beans (Red) (1 KG, Index Weight = 1), Cassava ...",SSP,2007-01-01,2023-08-01,30,30,9,"beans: 2067, cassava: 534, groundnuts: 1569, m...",...,63524.56%,47.02%,-29.43%,22.75%,0.67,0.97,"beans: 0.91, cassava: 0.91, groundnuts: 0.88, ...","fuel_diesel: 0.9, fuel_petrol_gasoline: 0.9",0.90,"beans: cubist (Andree, 2021), cassava: two-sta..."
22,Syrian Arab Republic,SYR,"Apples (1 KG, Index Weight = 1), Bananas (1 KG...",SYP,2011-02-01,2023-07-01,97,97,24,"apples: 3631, bananas: 3479, beans: 4117, brea...",...,4135.12%,34.15%,-13.96%,12.68%,0.60,0.96,"apples: 0.91, bananas: 0.91, beans: 0.96, brea...","exchange_rate_wfp: 0.98, fuel_diesel: 0.97, fu...",0.95,"apples: two-stage cubist (Andree and Pape, 202..."
23,Chad,TCD,"Maize (White) (1 KG, Index Weight = 1), Millet...",XAF,2007-01-01,2023-08-01,62,62,4,"maize: 2885, millet: 4683, rice: 2096, sorghum...",...,68.28%,3.16%,-32.67%,12.58%,0.58,0.79,"maize: 0.84, millet: 0.85, rice: 0.95, sorghum...","livestockgoat_castrated_male: 0.71, livestocks...",0.89,"maize: two-stage cubist (Andree and Pape, 2023..."
24,"Yemen, Rep.",YEM,"Beans (Kidney Red) (1 KG, Index Weight = 1), E...",YER,2009-01-01,2023-07-01,24,24,15,"beans: 2295, eggs: 2239, lentils: 2211, millet...",...,524.33%,13.22%,-14.88%,10.65%,0.55,0.75,"beans: 0.94, eggs: 0.97, lentils: 0.93, millet...","exchange_rate_wfp: 0.99, fuel_diesel: 0.91, fu...",0.95,"beans: cubist (Andree, 2021), eggs: cubist (An..."

In [ ]:
details=details.drop_duplicates()
details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 23 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   country                                                 25 non-null     object
 1   iso3                                                    25 non-null     object
 2   components                                              25 non-null     object
 3   currency                                                25 non-null     object
 4   start_date_observations                                 25 non-null     datetime64[ns]
 5   end_date_observations                                   25 non-null     datetime64[ns]
 6   number_of_markets_modeled                               25 non-null     int64
 7   number_of_markets_covered                               25 non-null     int64
 8   number_of_food_items                                    25 non-null     int64
 9   number_of_observations_food                             25 non-null     object
 10  number_of_observations_other                            25 non-null     object
 11  data_coverage_food                                      25 non-null     object
 12  data_coverage_previous_12_months_food                   25 non-null     object
 13  total_food_price_increase_since_start_date              25 non-null     object
 14  average_annualized_food_inflation                       25 non-null     object
 15  maximum_food_drawdown                                   25 non-null     object
 16  average_annualized_food_volatility                      25 non-null     object
 17  average_monthly_food_price_correlation_between_markets  25 non-null     float64
 18  average_annual_food_price_correlation_between_markets   25 non-null     float64
 19  Rsquared_individual_food_items                          25 non-null     object
 20  Rsquared_individual_other_items                         25 non-null     object
 21  index_confidence_score                                  25 non-null     float64
 22  imputation_model                                        25 non-null     object
dtypes: datetime64[ns](2), float64(3), int64(3), object(15)
memory usage: 4.6+ KB